version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d url_shortener"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres  
      DB_PORT: "5432"
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: url_shortener
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: